[package]
name = "tetris"
version = "0.1.0"
authors = ["A.I. <merrick@luois.me>"]

[dependencies]
chrono = "0.2.25"
timer = "0.1.6"
rand = "0.3.14"
piston = "0.25.0"
piston2d-graphics = "0.17.0"
pistoncore-glutin_window = "0.30.0"
piston2d-opengl_graphics = "0.33.0"
